site_name: Delphyne
theme:
  name: material
  favicon: null
  # favicon: assets/logos/black/21.png
  logo: assets/logos/white/mini.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.indexes  # Allows adding welcome pages to sections
    # - navigation.tabs
    # - navigation.sections  # Make left navigation bar not foldable

plugins:
  # - glightbox  # To allow clicking on images to view them in a lightbox
  - search  # add search bar
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            cross_references: true
            show_signature_annotations: true  # show types in signatures
            separate_signature: true  # show signatures in separate blocks
            filters: ["!^_"]  # do not show private members
            signature_crossrefs: true  # render links in signatures
            line_length: 88  # line length for signatures

markdown_extensions:
  - admonition  # Boxes such as 'info', 'question', 'warning'...
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html  # allows using markdown inside of HTML elements
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      base_path: [.]
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascript/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

extra:
  version:
    provider: mike

nav:
  - index.md
  - Manual:
    - manual/strategies.md
    - manual/policies.md
    - manual/demos.md
    - manual/extension.md
  - how-to-guides.md
  - Reference:
    # - reference/index.md
    - Strategies:
      - Trees: reference/strategies/trees.md
      - Queries: reference/strategies/queries.md
      - Traces: reference/strategies/traces.md
      - Misc: reference/strategies/misc.md
    - Policies:
      - Definitions: reference/policies/definitions.md
      - Search Streams: reference/policies/streams.md
      - Environments: reference/policies/envs.md
    - Demonstrations:
      - Definitions: reference/demos/definitions.md
      - Interpreter: reference/demos/interpreter.md
    - Standard Library:
      - Basic: reference/stdlib/basic.md
      - Queries: reference/stdlib/queries.md
      - Streams: reference/stdlib/streams.md
      - Effects: reference/stdlib/effects.md
      - Algorithms: reference/stdlib/algorithms.md
      - Commands: reference/stdlib/commands.md
      - Experiments: reference/stdlib/experiments.md

# TODO: add `examples` section