"""
Generate the Ladon selection partition (`ladon/ladonX.txt`) deterministically.

Why it exists. validationX has been read for selection by every arm
since 2026-08-25 (ACE offline, online, strong, v5), so an autonomous
loop that kept selecting on it would accumulate winner's-curse bias
night after night (HINTS #67). Ladon therefore selects on its own
partition, drawn from what the X partitions left unused, and never
touches testX: a KEEP's testX look is Guille's decision in the morning.

The rule, in order (all executable; `--check` proves the file matches):

1. **Universe** — the X universe (`miniF2F/valid/` + `miniF2F/test/`
   minus the original partitions, the ACE adaptation pool and the
   demos, `parse` screen; `tools/make_partitions.py`) minus the three
   X partitions themselves. 205 problems on 2026-09-02.
2. **Family mix** — `LADON_MIX`: every remaining `imo` (5) and `aime`
   (3), then `amc` 14, `mathd/algebra` 9, `mathd/numbertheory` 9 = 40.
   `induction` and `algebra` are exhausted (the X partitions took the
   last of them). Largest-remainder apportionment capped by
   availability, the same helper the X partitions use.
3. **Deal** — categories in `LADON_ORDER`; within a category,
   candidates in stem order (`valid` before `test`); the first `quota`
   of each. No hand-picking anywhere.
4. **File order** — categories interleaved round-robin, the X
   convention: a category-blocked file front-loads the AIME problems
   that each burn the whole budget.

The three X files are not read for anything but exclusion and are
never rewritten here; `tools/make_partitions.py --check` stays the
guard for them.

Usage:
    python -m ladon.make_partition            # write ladon/ladonX.txt
    python -m ladon.make_partition --check    # regenerate, diff, exit 1
    python -m ladon.make_partition --report   # print, write nothing
"""

# pyright: strict

import argparse
import sys
from collections.abc import Mapping, Sequence
from datetime import date
from pathlib import Path

_OMPHALOS_DIR = Path(__file__).resolve().parent.parent
for _sub in ("", "tools"):
    _p = str(_OMPHALOS_DIR / _sub)
    if _p not in sys.path:
        sys.path.insert(0, _p)

from make_partitions import (  # noqa: E402
    X_FILES,
    _same_modulo_date,  # pyright: ignore[reportPrivateUsage]
    excluded_stems,
)
from make_pool import (  # noqa: E402
    _candidates,  # pyright: ignore[reportPrivateUsage]
    _category,  # pyright: ignore[reportPrivateUsage]
    _quotas,  # pyright: ignore[reportPrivateUsage]
)

LADON_FILE = "ladon/ladonX.txt"

ROLE = (
    "LADON-X — selection partition of the Ladon overnight loop: every\n"
    "# Ladon arm is paired against the canonical baseline here (two\n"
    "# seeds). Never a headline partition; testX keeps the clean look."
)

LADON_MIX: Mapping[str, int] = {
    "imo": 5,
    "aime": 3,
    "amc": 14,
    "mathd/algebra": 9,
    "mathd/numbertheory": 9,
}
"""40 problems: everything competition-grade that is left, then mathd."""

LADON_ORDER: Sequence[str] = tuple(LADON_MIX)
"""Deal order and interleave order — hardest categories first."""

SIZE = sum(LADON_MIX.values())


def ladon_excluded_stems() -> set[str]:
    """The X exclusions plus the three X partitions themselves."""
    stems = excluded_stems()
    for rel in X_FILES.values():
        for raw in (_OMPHALOS_DIR / rel).read_text().splitlines():
            line = raw.strip()
            if line and not line.startswith("#"):
                stems.add(Path(line).stem)
    return stems


def build() -> tuple[dict[str, list[Path]], dict[str, int], dict[str, int]]:
    """`{category: [paths]}`, the quotas and the availability counts."""
    avail_paths, _drops = _candidates(["parse"], ladon_excluded_stems())
    avail = {c: len(v) for c, v in avail_paths.items()}
    quota = _quotas(LADON_MIX, avail, SIZE)
    assert sum(quota.values()) == SIZE, quota
    chosen: dict[str, list[Path]] = {}
    for cat in LADON_ORDER:
        picks = avail_paths.get(cat, [])[: quota.get(cat, 0)]
        assert all(_category(p) == cat for p in picks)
        chosen[cat] = picks
    return chosen, quota, avail


def _interleave(by_cat: Mapping[str, list[Path]]) -> list[Path]:
    queues = {c: list(v) for c, v in by_cat.items()}
    out: list[Path] = []
    while any(queues.values()):
        for cat in LADON_ORDER:
            if queues[cat]:
                out.append(queues[cat].pop(0))
    return out


def render() -> str:
    by_cat, quota, avail = build()
    chosen = _interleave(by_cat)
    lines = [
        f"# {ROLE}",
        "#",
        "# GENERATED by ladon/make_partition.py — do not edit by hand.",
        "# Regenerate: python -m ladon.make_partition",
        f"# Verify:     python -m ladon.make_partition --check   ({date.today()})",
        "#",
        "# Rule: universe = the X universe minus trainX/validationX/testX;",
        f"# family mix {dict(LADON_MIX)} (largest remainder, capped by",
        "# availability; induction/algebra are exhausted); dealt in stem",
        "# order; categories interleaved in the file body. Reserved for the",
        "# luna-class pipeline the Ladon loop improves.",
        "#",
        "# per category (chosen / quota / available):",
    ]
    for cat in LADON_ORDER:
        lines.append(
            f"#   {cat:<22} {len(by_cat[cat]):>3} / {quota.get(cat, 0):>3}"
            f" / {avail.get(cat, 0):>3}"
        )
    lines.append(f"# total: {len(chosen)}")
    lines.append("")
    body = "\n".join(str(p.relative_to(_OMPHALOS_DIR)) for p in chosen)
    return "\n".join(lines) + "\n" + body + "\n"


def _count(text: str) -> int:
    return sum(
        1
        for line in text.splitlines()
        if line.strip() and not line.startswith("#")
    )


def check() -> list[str]:
    """Drift lines (empty = the file matches its rule)."""
    target = _OMPHALOS_DIR / LADON_FILE
    text = render()
    if not target.exists():
        return [f"missing {LADON_FILE}; run without --check to create it"]
    if not _same_modulo_date(target.read_text(), text):
        return [f"{LADON_FILE} has drifted from its generation rule"]
    return []


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Generate the Ladon selection partition deterministically "
            "from the miniF2F problems the X partitions left unused. "
            "Makes no API calls."
        )
    )
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--report", action="store_true")
    args = parser.parse_args()
    if args.report:
        print(render())
        return 0
    if args.check:
        drift = check()
        for line in drift:
            print(line)
        if not drift:
            print(
                f"{LADON_FILE}: {_count(render())} problems, matches the rule"
            )
        return 1 if drift else 0
    target = _OMPHALOS_DIR / LADON_FILE
    text = render()
    target.write_text(text)
    print(f"Wrote {LADON_FILE}: {_count(text)} problems")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
