"""
Generate the ACE adaptation pool deterministically.

The three benchmark partitions were hand-maintained: their selection
rule lives only in file-header prose, and `benchmarks/test.txt` already
contains one undocumented deviation from it. This script makes the rule
for the *adaptation* pool executable and checkable instead, so the pool
cannot drift from its own definition.

The pool is adaptation-only. It is never evaluated, so it does not have
to preserve any distributional property of the partitions — but it is
drawn to resemble them anyway, because a playbook learned from a wildly
different mix would confound "ACE does not help here" with "ACE learned
about the wrong problems".

The rule, in order:

1. **Universe** — every `.v` file under `miniF2F/valid/` and
   `miniF2F/test/` (488 files, stems globally unique).
2. **Exclusions** — every problem in `benchmarks/{train,validation,
   test}.txt` and the three demonstration problems, excluded by *stem*
   as well as by path, since configs are keyed on the stem.
3. **Screens**, each reported with its drop count:
   - `aux` — drop files carrying `Definition`/`Fixpoint`/`Notation`/
     `Inductive`/`Record`/`Axiom`/`Parameter` declarations in their
     preamble. `pytanque_utils.parse_problem` captures only
     `Require`/`Import`/`Open Scope`, so on those files the model is
     shown a theorem referencing symbols it never sees — an unwinnable
     prompt that would teach the Reflector a bogus lesson. Disable with
     `--screen=none` (the generated header records which screens ran).
   - `parse` — drop anything `parse_problem` rejects or that yields an
     empty theorem statement.
4. **Apportionment** — per-category quotas proportional to the current
   60-problem partition mix, by largest remainder, capped at what each
   category still has. `miniF2F/valid` alone cannot honour that mix
   (its `induction/` and `numbertheory/` are exhausted and `algebra/`
   has one file left), which is why the untouched `miniF2F/test` split
   is in the universe: its stems are disjoint, its format identical,
   and omphalos evaluates nothing from it. Shortfalls are redistributed
   over the categories that still have capacity.
5. **Order within a category** — `valid` files first, then `test`, each
   by stem; take the quota from the front.

Note that miniF2F's own `test/` split is unrelated to omphalos's
`benchmarks/test.txt`, which is drawn from miniF2F `valid/`. Nothing
leaks: step 2 excludes the evaluated problems by name.

Usage:
    python -m tools.data.make_pool --size 100          # write the pool file
    python -m tools.data.make_pool --check             # regenerate, diff, exit 1 on drift
    python -m tools.data.make_pool --report            # print the screens, write nothing
"""

from runtime.paths import OMPHALOS_ROOT

# pyright: strict

import argparse
import re
from collections.abc import Mapping, Sequence
from datetime import date
from pathlib import Path


import runtime.pytanque_utils as pt  # noqa: E402

_OMPHALOS_DIR = OMPHALOS_ROOT

_DATE_RE = re.compile(r"\(\d{4}-\d{2}-\d{2}\)")


def _same_modulo_date(a: str, b: str) -> bool:
    """
    Equality that ignores the generation date in the header, so that
    `--check` still passes the day after the file was written.
    """

    # Frozen partition headers retain their original generation command.
    # Normalize only that spelling; the selection and all other metadata
    # must still match exactly.
    def normalize(text: str) -> str:
        for script in ("make_pool", "make_partitions"):
            text = text.replace(
                f"python tools/{script}.py", f"python -m tools.data.{script}"
            )
        text = text.replace(
            "# GENERATED by tools/make_partitions.py",
            "# GENERATED by tools/data/make_partitions.py",
        )
        return _DATE_RE.sub("(date)", text)

    return normalize(a) == normalize(b)


DEFAULT_OUT = "benchmarks/adapt_pool.txt"
DEFAULT_SIZE = 100

PARTITION_FILES = (
    "benchmarks/train.txt",
    "benchmarks/validation.txt",
    "benchmarks/test.txt",
)

DEMO_PROBLEMS = (
    "algebra_binomnegdiscrineq_10alt28asqp1",
    "induction_sum_odd",
    "mathd_numbertheory_136",
)

_AUX_RE = re.compile(
    r"^\s*(?:Local\s+)?"
    r"(?:Definition|Fixpoint|Notation|Inductive|Record|Axiom|Parameter)\b",
    re.MULTILINE,
)

_COMMENT_RE = re.compile(r"\(\*.*?\*\)", re.DOTALL)


def _category(path: Path) -> str:
    """`mathd/algebra`, `imo`, ... — the directory under the split."""
    rel = path.relative_to(_OMPHALOS_DIR / "miniF2F")
    return "/".join(rel.parts[1:-1])


def _preamble(text: str) -> str:
    """Everything before the first `Theorem`, comments stripped."""
    return _COMMENT_RE.sub("", text).split("Theorem ")[0]


def _excluded_stems() -> set[str]:
    stems: set[str] = set(DEMO_PROBLEMS)
    for pf in PARTITION_FILES:
        for raw in (_OMPHALOS_DIR / pf).read_text().splitlines():
            line = raw.strip()
            if line and not line.startswith("#"):
                stems.add(Path(line).stem)
    return stems


def _partition_mix() -> dict[str, int]:
    """Category counts across the three partitions (the target mix)."""
    mix: dict[str, int] = {}
    for pf in PARTITION_FILES:
        for raw in (_OMPHALOS_DIR / pf).read_text().splitlines():
            line = raw.strip()
            if line and not line.startswith("#"):
                cat = _category(_OMPHALOS_DIR / line)
                mix[cat] = mix.get(cat, 0) + 1
    return mix


def _candidates(
    screens: Sequence[str],
    excluded: set[str] | None = None,
) -> tuple[dict[str, list[Path]], dict[str, int]]:
    """
    Surviving candidates per category, plus per-screen drop counts.

    `excluded` defaults to the three partitions plus the demos; the X
    partitions (`tools/data/make_partitions.py`) pass a wider set.
    """
    if excluded is None:
        excluded = _excluded_stems()
    drops = {"excluded": 0, "aux": 0, "parse": 0}
    out: dict[str, list[Path]] = {}
    for split in ("valid", "test"):
        root = _OMPHALOS_DIR / "miniF2F" / split
        for path in sorted(root.rglob("*.v"), key=lambda p: p.stem):
            if path.stem in excluded:
                drops["excluded"] += 1
                continue
            text = path.read_text()
            if "aux" in screens and _AUX_RE.search(_preamble(text)):
                drops["aux"] += 1
                continue
            if "parse" in screens:
                try:
                    spec = pt.parse_problem(str(path))
                except Exception:
                    drops["parse"] += 1
                    continue
                if not spec.theorem_statement.strip():
                    drops["parse"] += 1
                    continue
                assert spec.theorem_name == path.stem, (
                    f"{path}: theorem name {spec.theorem_name!r} does"
                    " not match the filename stem; config identities"
                    " are keyed on the stem"
                )
            out.setdefault(_category(path), []).append(path)
    # `valid` before `test` within each category, each already by stem.
    for cat in out:
        out[cat].sort(key=lambda p: (0 if "/valid/" in str(p) else 1, p.stem))
    return out, drops


def _quotas(
    mix: Mapping[str, int], avail: Mapping[str, int], size: int
) -> dict[str, int]:
    """
    Largest-remainder apportionment of `size` over the partition mix,
    capped by availability, with the shortfall redistributed over the
    categories that still have room.
    """
    total = sum(mix.values())
    exact = {c: size * n / total for c, n in mix.items()}
    quota = {c: min(int(v), avail.get(c, 0)) for c, v in exact.items()}
    while sum(quota.values()) < size:
        room = [c for c in mix if quota.get(c, 0) < avail.get(c, 0)]
        if not room:
            break
        # Largest fractional remainder first, then the category that is
        # furthest below its exact share, then alphabetically.
        room.sort(
            key=lambda c: (
                -(exact[c] - quota[c]),
                c,
            )
        )
        quota[room[0]] = quota.get(room[0], 0) + 1
    return quota


def build(size: int, screens: Sequence[str]) -> tuple[list[Path], str]:
    """Return the selected paths and the header to write above them."""
    avail_paths, drops = _candidates(screens)
    avail = {c: len(v) for c, v in avail_paths.items()}
    mix = _partition_mix()
    quota = _quotas(mix, avail, size)
    chosen: list[Path] = []
    for cat in sorted(quota):
        chosen.extend(avail_paths.get(cat, [])[: quota[cat]])
    lines = [
        "# ACE adaptation pool — GENERATED, do not edit by hand.",
        f"# Regenerate: python -m tools.data.make_pool --size {size}"
        f" --screen {','.join(screens) if screens else 'none'}",
        f"# Verify:     python -m tools.data.make_pool --check   ({date.today()})",
        "#",
        "# Adaptation only: these problems are never evaluated. Drawn",
        "# from miniF2F valid/ AND test/ — miniF2F's own test split is",
        "# unrelated to benchmarks/test.txt (which comes from valid/),",
        "# and every problem in every partition is excluded by stem.",
        "#",
        f"# screens: {','.join(screens) if screens else 'none'}"
        f"   dropped: {drops}",
        "# per category (selected/available):",
    ]
    for cat in sorted(quota):
        lines.append(f"#   {cat:<22} {quota[cat]:>3} / {avail.get(cat, 0):>3}")
    lines.append(f"# total: {len(chosen)}")
    lines.append("")
    return chosen, "\n".join(lines)


def render(size: int, screens: Sequence[str]) -> str:
    chosen, header = build(size, screens)
    body = "\n".join(str(p.relative_to(_OMPHALOS_DIR)) for p in chosen)
    return f"{header}\n{body}\n"


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Generate the ACE adaptation pool deterministically from "
            "the unused miniF2F problems. Makes no API calls."
        )
    )
    parser.add_argument("--out", default=DEFAULT_OUT)
    parser.add_argument("--size", type=int, default=DEFAULT_SIZE)
    parser.add_argument(
        "--screen",
        default="aux,parse",
        help="comma list of screens, or 'none'",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate in memory and fail if the file has drifted",
    )
    parser.add_argument(
        "--report",
        action="store_true",
        help="print the selection and write nothing",
    )
    args = parser.parse_args()

    raw_screens = str(args.screen)
    screens = (
        [] if raw_screens == "none" else [s for s in raw_screens.split(",")]
    )
    text = render(int(args.size), screens)
    target = _OMPHALOS_DIR / str(args.out)

    if args.report:
        print(text)
        return 0
    if args.check:
        if not target.exists():
            print(f"missing {args.out}; run without --check to create it")
            return 1
        if not _same_modulo_date(target.read_text(), text):
            print(
                f"{args.out} has drifted from its generation rule; "
                "regenerate it or explain the deviation in its header"
            )
            return 1
        n = sum(
            1
            for line in text.splitlines()
            if line.strip() and not line.startswith("#")
        )
        print(f"{args.out}: {n} problems, matches the rule")
        return 0

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text)
    n = sum(
        1
        for line in text.splitlines()
        if line.strip() and not line.startswith("#")
    )
    print(f"Wrote {args.out}: {n} problems")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
