"""
Generate the X partitions (`trainX` / `validationX` / `testX`) deterministically.

Why they exist. The original 20-problem partitions saturated: train is
20/20 for every toolset, validation and test are 16/20 with the *same*
sixteen for terra and luna, and ACE came back with zero discordant
cells on test. At n=20 an exact sign test needs six discordant problems
all one way while identical configurations already disagree on one to
three, so those partitions can no longer rank anything the cheap
pipelines do. The X partitions are larger (40 each) and harder (half
competition problems, plus every remaining problem whose file declares
its own `Definition`/`Fixpoint`/`Notation` — usable now that the prompt
shows them, see `pytanque_utils.parse_problem`).

Who runs on them. **Only pipelines at luna's cost class** — the
canonical `gpt-5.6-luna` / `core` / `medium` / Responses configuration
and everything built on it (ACE, two-tier policies, ...). The terra/sol
frontier and the chat-completions baselines keep the original
partitions; their story is told there and re-running them here would
cost an order of magnitude more for no new decision.

The rule, in order (all of it executable; `--check` proves the files
still match it):

1. **Universe** — every `.v` under `miniF2F/valid/` and `miniF2F/test/`
   (488 files, stems globally unique). miniF2F's own `test/` split is
   unrelated to `benchmarks/test.txt`; nothing leaks because step 2
   excludes by stem.
2. **Exclusions** — the three original partitions, the ACE adaptation
   pool (`benchmarks/adapt_pool.txt`) and the demonstration problems,
   by stem. 163 problems, leaving 325.
3. **Screen** — only `parse` (the file parses and its theorem name is
   its stem). No `aux` screen: files with pre-theorem declarations are
   wanted, not dropped.
4. **Family mix** — 120 problems apportioned per category by largest
   remainder over `FAMILY_MIX` (imo 15, aime 12, amc 33, induction 3,
   algebra 2, mathd/algebra 28, mathd/numbertheory 27), capped by
   availability. That is 50% competition problems against ~35% in the
   original partitions; `induction`/`algebra` are simply everything
   that is left.
5. **Deal** — categories in `CATEGORY_ORDER`; within a category,
   candidates in stem order (`valid` before `test`); every candidate
   goes to the next partition of a single round-robin pointer that runs
   across categories, so the three partitions get 40 problems each and
   the same category counts to within one. No hand-picking anywhere.
6. **File order** — each partition file interleaves its categories
   (round-robin over `CATEGORY_ORDER`) instead of listing them in
   blocks. A category-blocked file opens a sweep on eleven AIME
   problems that each burn the whole budget (`PROGRESS.md`, the
   adaptation pool's ~4 h). This order is also the pre-registered
   traversal order of online adaptation.

Usage:
    python -m tools.data.make_partitions            # write the three files
    python -m tools.data.make_partitions --check    # regenerate, diff, exit 1 on drift
    python -m tools.data.make_partitions --report   # print, write nothing
"""

# pyright: strict

import argparse
import re
from collections.abc import Mapping, Sequence
from datetime import date
from pathlib import Path


from tools.data.make_pool import (  # noqa: E402
    _OMPHALOS_DIR,  # pyright: ignore[reportPrivateUsage]
    DEFAULT_OUT as ADAPT_POOL_FILE,
    _candidates,  # pyright: ignore[reportPrivateUsage]
    _category,  # pyright: ignore[reportPrivateUsage]
    _excluded_stems,  # pyright: ignore[reportPrivateUsage]
    _quotas,  # pyright: ignore[reportPrivateUsage]
)

_DATE_RE = re.compile(r"\(\d{4}-\d{2}-\d{2}\)")


def _same_modulo_date(a: str, b: str) -> bool:
    """
    Equality that ignores the generation date in the header, so that
    `--check` still passes the day after the file was written.
    """

    # Frozen partition headers retain their original generation command.
    # Normalize only that spelling; the selection and all other metadata
    # must still match exactly.
    def normalize(text: str) -> str:
        for script in ("make_pool", "make_partitions"):
            text = text.replace(
                f"python tools/{script}.py", f"python -m tools.data.{script}"
            )
        text = text.replace(
            "# GENERATED by tools/make_partitions.py",
            "# GENERATED by tools/data/make_partitions.py",
        )
        return _DATE_RE.sub("(date)", text)

    return normalize(a) == normalize(b)


X_FILES: Mapping[str, str] = {
    "trainX": "benchmarks/trainX.txt",
    "validationX": "benchmarks/validationX.txt",
    "testX": "benchmarks/testX.txt",
}

ROLES: Mapping[str, str] = {
    "trainX": (
        "TRAIN-X — tuning partition for the luna-class pipelines: caps are\n"
        "# derived here, playbooks are adapted here, sweeps are ranked here."
    ),
    "validationX": (
        "VALIDATION-X — selection partition: arms tuned on trainX are\n"
        "# compared here (two seeds) and the winner goes to testX. Online\n"
        "# adaptation is developed here."
    ),
    "testX": (
        "TEST-X — the clean partition: one look per headline arm, never\n"
        "# mined for fixes, never adapted on, never used to pick anything."
    ),
}

FAMILY_MIX: Mapping[str, int] = {
    "imo": 15,
    "aime": 12,
    "amc": 33,
    "induction": 3,
    "algebra": 2,
    "mathd/algebra": 28,
    "mathd/numbertheory": 27,
}
"""120 problems, competition-heavy; see the module docstring."""

CATEGORY_ORDER: Sequence[str] = tuple(FAMILY_MIX)
"""Deal order and interleave order — hardest categories first."""

TOTAL = sum(FAMILY_MIX.values())
N_PARTITIONS = len(X_FILES)
assert TOTAL % N_PARTITIONS == 0


def excluded_stems() -> set[str]:
    """The original partitions and demos, plus the adaptation pool."""
    stems = _excluded_stems()
    for raw in (_OMPHALOS_DIR / ADAPT_POOL_FILE).read_text().splitlines():
        line = raw.strip()
        if line and not line.startswith("#"):
            stems.add(Path(line).stem)
    return stems


def build() -> tuple[
    dict[str, dict[str, list[Path]]], dict[str, int], dict[str, int]
]:
    """
    Return `{partition: {category: [paths]}}` (categories in
    `CATEGORY_ORDER`, paths in stem order), the per-category quotas and
    the availability counts.
    """
    avail_paths, _drops = _candidates(["parse"], excluded_stems())
    avail = {c: len(v) for c, v in avail_paths.items()}
    quota = _quotas(FAMILY_MIX, avail, TOTAL)
    assert sum(quota.values()) == TOTAL, quota
    names = list(X_FILES)
    dealt: dict[str, dict[str, list[Path]]] = {
        n: {c: [] for c in CATEGORY_ORDER} for n in names
    }
    pointer = 0
    for cat in CATEGORY_ORDER:
        for path in avail_paths.get(cat, [])[: quota.get(cat, 0)]:
            assert _category(path) == cat
            dealt[names[pointer % N_PARTITIONS]][cat].append(path)
            pointer += 1
    return dealt, quota, avail


def _interleave(by_cat: Mapping[str, list[Path]]) -> list[Path]:
    queues = {c: list(v) for c, v in by_cat.items()}
    out: list[Path] = []
    while any(queues.values()):
        for cat in CATEGORY_ORDER:
            if queues[cat]:
                out.append(queues[cat].pop(0))
    return out


def render(name: str) -> str:
    dealt, quota, avail = build()
    by_cat = dealt[name]
    chosen = _interleave(by_cat)
    lines = [
        f"# {ROLES[name]}",
        "#",
        "# GENERATED by tools/data/make_partitions.py — do not edit by hand.",
        "# Regenerate: python -m tools.data.make_partitions",
        f"# Verify:     python -m tools.data.make_partitions --check   ({date.today()})",
        "#",
        "# Rule: universe = miniF2F valid/ + test/ minus train/validation/",
        "# test, the ACE adaptation pool and the demos (by stem); family mix",
        f"# {dict(FAMILY_MIX)}",
        "# dealt round-robin across trainX/validationX/testX in stem order;",
        "# categories interleaved in the file body (this is also the online",
        "# adaptation order). Reserved for luna-class pipelines only.",
        "#",
        "# per category (this partition / family quota / available):",
    ]
    for cat in CATEGORY_ORDER:
        lines.append(
            f"#   {cat:<22} {len(by_cat[cat]):>3} / {quota.get(cat, 0):>3}"
            f" / {avail.get(cat, 0):>3}"
        )
    lines.append(f"# total: {len(chosen)}")
    lines.append("")
    body = "\n".join(str(p.relative_to(_OMPHALOS_DIR)) for p in chosen)
    return "\n".join(lines) + "\n" + body + "\n"


def _count(text: str) -> int:
    return sum(
        1
        for line in text.splitlines()
        if line.strip() and not line.startswith("#")
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Generate the X partitions deterministically from the unused "
            "miniF2F problems. Makes no API calls."
        )
    )
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--report", action="store_true")
    args = parser.parse_args()

    rendered = {n: render(n) for n in X_FILES}
    if args.report:
        for n, text in rendered.items():
            print(f"===== {X_FILES[n]}")
            print(text)
        return 0
    drifted = False
    for n, text in rendered.items():
        target = _OMPHALOS_DIR / X_FILES[n]
        if args.check:
            if not target.exists():
                print(
                    f"missing {X_FILES[n]}; run without --check to create it"
                )
                drifted = True
            elif not _same_modulo_date(target.read_text(), text):
                print(f"{X_FILES[n]} has drifted from its generation rule")
                drifted = True
            else:
                print(
                    f"{X_FILES[n]}: {_count(text)} problems, matches the rule"
                )
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text)
        print(f"Wrote {X_FILES[n]}: {_count(text)} problems")
    return 1 if drifted else 0


if __name__ == "__main__":
    raise SystemExit(main())
